name: aiven - Deploy Kafka-topics

on:
  push:
    branches:
      - main
    paths:
      - '.nais/sis.yaml'
      - '.nais/sis.*.yaml'
      - '.nais/utbetaling.yaml'
      - '.nais/utbetaling.*.yaml'
      - '.nais/vedtak.yaml'
      - '.nais/vedtak.*.yaml'
      - '.github/workflows/topic.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write # for nais login

jobs:
  deploy-dev:
    name: Deploy til dev
    uses: navikt/sykepenger-github-workflows/.github/workflows/deploy-v2.yml@77c349d62b631cf0fedc02278c68abd33bc8ea5b # v1.0.10
    with:
      manifest: .nais/utbetaling.yaml
      environment: dev-gcp
      extra_manifests: .nais/vedtak.yaml,.nais/sis.yaml
    permissions:
      contents: read
      id-token: write # for nais login

  deploy-prod:
    name: Deploy til prod
    uses: navikt/sykepenger-github-workflows/.github/workflows/deploy-v2.yml@77c349d62b631cf0fedc02278c68abd33bc8ea5b # v1.0.10
    with:
      manifest: .nais/utbetaling.yaml
      environment: prod-gcp
      extra_manifests: .nais/vedtak.yaml,.nais/sis.yaml
    permissions:
      contents: read
      id-token: write # for nais login
